# Generated by Django 3.1.1 on 2021-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_auto_20210427_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Phone_pey', 'Phone_pey'), ('Google_pay', 'Google_pay'), ('Pay_on_delivery', 'Pay_on_delivery')], default=None, max_length=20, null=True),
        ),
    ]
