# Generated by Django 3.1.1 on 2021-05-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0019_auto_20210502_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorders',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
