# Generated by Django 3.1.1 on 2021-05-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0020_customerorders_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorders',
            name='ordered_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
